### ISSUE TITLE
Support for the smol runtime

### ISSUE THREAD

**Issue by qdot** [najamelan/async_executors#1]
smol is already used under async_std 1.6.0, but it might be worth supporting it separately since it's kind of its own thing.

**Comment by najamelan** [comment]
Could you clarify your use case? AFAICT smol works by rapping async code in a `run` function. As async_executors provides executors as objects, we would have to encapsulate that, but that's more or less what async-std does.

**Comment by najamelan** [comment]
In the mean time, async_executors also supports the `async-global-executor`, which is a more stripped down wrapper around smol. Do you still feel there is an advantage to supporting smol directly? AFAICT we would have to more or less rewrite `async-global-executor` in this crate. What do you think?

**Comment by qdot** [comment]
Oh! Totally forgot I filed this... a year ago. >.>

I've moved to just running either tokio or wasm-bindgen's executor now depending on context, so I no longer really have the usecase I originally filed this for. If you aren't seeing any other requests on smol, I'm guessing this is closable.

**Comment by najamelan** [comment]
Ok, yes I'll close it now. Smol only provides a thread local executor and async-global-executor exposes that to spawn `!Send` futures, so I feel it pretty much covers it.
