### ISSUE TITLE
Remove notwasm feature

### ISSUE THREAD

**Issue by qiujiangkun** [najamelan/async_executors#10]
Once you specify each test with its feature, and have `#![cfg(target = "wasm")]`,it should work fine without notwasm feature.
See https://github.com/qiujiangkun/async_executors/blob/dev/Cargo.toml

Though I can't get wasm working in my machine either way(it stucks during installation of wasm). You can try it out though.

**Comment by najamelan** [comment]
> Once you specify each test with its feature, and have #![cfg(target = "wasm")],it should work fine without notwasm feature.

No it doesn't: 
- https://github.com/rustwasm/wasm-pack/issues/666
- https://github.com/rust-lang/cargo/issues/7233

All these inconveniences in the code are there for a reason. Not because I like them. I don't like `notwasm` feature, but I have no way to get it to work without.

**Comment by najamelan** [comment]
As this is blocked for the moment I will close it for now. Feel free to re-open if there is a solution.
