### ISSUE TITLE
std::atomic::Ordering in JoinHandle

### ISSUE THREAD

**Issue by qiujiangkun** [najamelan/async_executors#12]
Do we need to make JoinHandle Sync?
In most of the case `.await` consumes the JoinHandle, so It doesn't matter if we use `AtomicBool`.
Only `Ordering::Relaxed` is used in JoinHanle, so can we just use bool if we don't need `Sync`?

**Comment by najamelan** [comment]
You are right, it does not need to be atomic. It will still be `Sync` just the same btw. Fixed in https://github.com/najamelan/async_executors/commit/ef9fc51e43a73da2e3d6ad5a0de4ca9018bcbf84.
