### ISSUE TITLE
Behaviors of JoinHandles for panicked and cancelled tasks

### ISSUE THREAD

**Issue by qiujiangkun** [najamelan/async_executors#16]
Currently almost all JoinHandles panicks when 1) the runtime panicks, 2) the task panicks, 3) the task gets cancelled
Can we have some designs to let them return an error?

**Comment by najamelan** [comment]
There is 2 ways to achieve this:
- don't panic in your futures, return an error
- wrap your futures in [catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html)
