### ISSUE TITLE
Support async-std 1.6

### ISSUE THREAD

**Issue by FractalU** [najamelan/async_executors#2]
Why not updating async_executors from 0.3.0-beta.1 to 0.3.0 and async_nursery from 0.1.0 to 0.1.1 to support async-std 1.6.0?

**Comment by najamelan** [comment]
I will get to it ASAP.

**Comment by FractalU** [comment]
Thanks for your response.

**Comment by najamelan** [comment]
Just released async_executors 0.3. async_nursery update coming soon.

**Comment by najamelan** [comment]
async_nursery 0.2 released.
