### ISSUE TITLE
Cleaner join handle Implementation

### ISSUE THREAD

**Issue by qiujiangkun** [najamelan/async_executors#9]
We can mimick async_trait so the JoinHandle is cleaner.
https://github.com/qiujiangkun/async_executors/blob/ade1cca94511feb569f203f309ed19e411995958/src/core/join_handle.rs#L18-L101

I have replaced all JoinHandles. If you like I can issue a PR

**Comment by najamelan** [comment]
I must say I don't quite understand what this does. Neither tokio nor async-std have a `detach` method. How is this even supposed to work?

Have you made sure all integration tests passed with this code?

**Comment by qiujiangkun** [comment]
Yes I have all tests passed. Tokio JH is here
https://github.com/qiujiangkun/async_executors/blob/ade1cca94511feb569f203f309ed19e411995958/src/runtime/tokio_jh.rs

**Comment by najamelan** [comment]
Ok, that is a different file. I will check it out tomorrow. I have to sleep soon.

**Comment by najamelan** [comment]
Ah, I see, so you create an interface and spread the logic of all joinhandles to different types in order to simplify JoinHandle. I mean we can do that, but in the end it means 5+ files, 6+ types 300+ SLOC to save maybe what, like 40 lines in join_handle.rs?

Is that really better?

**Comment by qiujiangkun** [comment]
Now initializing JoinHandle really isn't pretty
```rust
JoinHandle{
inner: InnerJH::Tokio{ handle: Some(xxx), ...}
}
```
I prefer
```rust
JoinHandle::new(TokioHandle::new(xxx))
```
Or better 
```rust
TokioHandle::new(xxx).into()
```

There are no TokioJoinHandle we can make use of. If we decide to remove `JoinHandle` some day to reduce JoinHandle overhead, ther is no way.
Unless
```rust
fn foo(exec: impl SpawnHandle) -> impl AsyncJoinHandle {
//    do something
}
```

**Comment by qiujiangkun** [comment]
As a alternative, I've opened a PR #11 that does't need much change

**Comment by najamelan** [comment]
PR #11 has been merged. I prefer to keep the logic together for now as I don't feel it's overwhelmingly complicated.
